import Header from "@/components/Header";
import ProductCard from "@/components/ProductCard";
import Head from "next/head";
import { getProducts } from "@/services";
import FilterWidget from "@/components/FilterWidget";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container mx-auto p-5 mb-8">
        <main className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          <div className="lg:col-span-3 col-span-1">
            <div className="lg:sticky relative top-8">
              <FilterWidget />
            </div>
          </div>
          <div className="lg:col-span-9 grid lg:grid-cols-3 grid-cols-1 col-span-1 gap-8">
            {products.map((product) => (
              <ProductCard key={product.node.name} product={product.node} />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const products = (await getProducts()) || [];

  return {
    props: { products },
  };
}
